### ISSUE TITLE
ChildIDs not being set for rerun transactions

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#410]
The childIDs element is being set for rerunned transactions anymore.

ParentID is still being set correctly.

**Comment by BMartinos** [comment]
So after a bit of investigation the problem is located at the updateTransaction function in the rerun middleware. https://github.com/jembi/openhim-core-js/blob/master/src/middleware/rerunUpdateTransactionTask.coffee#L8. 

The mongo validation seemed to be failing due to "request.method" or "request.path" doesnt exist
