### ISSUE TITLE
Validate clients domain against any certificate in the certification path

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#418]
In large deployments it may be difficult to setup clients for hundreds of PoC systems. Therefore it would be beneficial to be able to validate a client on their issuer rather than just the client certificate. In that case the issuer cert would be uploaded to the keystore and any clients with certs signed by that authority would be valid.

**Comment by bausmeier** [comment]
@devcritter I'm pretty sure this use case is already supported. If the issuer cert is in the list of trusted certs then as far as I know the client certs signed by that authority are considered valid.

**Comment by devcritter** [comment]
Thanks @bausmeier . It's good to know the ssl will pass. But I think I phrased this issue poorly! The problem I had in mind was how currently clients are looked up by client CN https://github.com/jembi/openhim-core-js/blob/master/src/middleware/tlsAuthentication.coffee#L64
i.e. so allowing for a client to be configured with an issuer in the `domain` field.

This came out of an issue @justin-fyfe raised. Justin does this cover what you had in mind? Or did I misunderstanding? :)

Of course if we proceed with #419 we would use fingerprint instead of CN.

**Comment by rcrichton** [comment]
I think we would have to think about this a bit. I'm not sure this is something we want. The certificate side of things is already handled, you will only need to install the issuer cert in the keystore. But for clients I think you do want a client per client system. If we don't then we circumvent our access control systems. Maybe that is something we want to support, but I'd say we should see the problem present itself in production before coming up with a solution.

**Comment by devcritter** [comment]
Ok sounds fine to me. So should we close this ticket and revisit if it becomes an implementation need?

**Comment by rcrichton** [comment]
Lets leave it open for now so others can comment if they would like. We can close this later if there are no comments.

**Comment by justin-fyfe** [comment]
Hi, 

The issue really only happens on HTTP channels accessed through the secure port with mutual authentication enabled (example: to web services through the HIM).  

For example, if I have two clients with two certs, say POC A (CN=poca.sample.org) and POC B (CN=pocb.sample.org) issued by the same CA (CN=ca.sample.org) and I want both POC A and POC B to have access to a channel on the HIM, I currently have to create two clients (with domains poca.sample.org and pocb.sample.org respectively). 

The desired state would to be able to create a client with a domain somewhere up the chain. For example, I would create one client called "trusted clients" with domain "ca.sample.org" and all clients with a cert in their chain from ca.sample.org would be granted access. Currently when I try to do this I get an "unauthorized" error on the client when accessing the channel using poca.sample.org or pocb.sample.org, and an error in the log saying the CN of the presented cert doesn't match what was expected.

Hope that helps clarify! 

Cheers
-Justin

**Comment by rcrichton** [comment]
Hey, @justin-fyfe thanks for that. I understand the problem. However, the expected use of the OpenHIM is that you should create a client for each system that want to connect so that you have a control over what systems can have access. I understand you could do this by with the certificate, but we also want to allow for more advanced access control (only certain clients access to certain channels). So, I'm not sure we want a 'catch-all' option for defining clients. The only reasoning I can see if for easier configuration, and I'm not sure that is valid reasoning. Perhaps we could make this easier in other ways? Otherwise, let me know if I'm missing another point.

**Comment by justin-fyfe** [comment]
I think 80% of the time clients who have a valid certificate issued by my HIE's CA will have access to most services in the HIE. I just don't think we should burden someone with configuring (and maintaining) a large list of individual clients when they've already done the work of gating them through the cert process (also if you proceed with #419 it will be more difficult to maintain as fingerprints change whenever a cert is re-issued due to expiry or revocation). 

Perhaps the issue should be reworded to "Validate Domain against any certificate in the certification path" as such a scheme would allow for both use cases. For example:

If I have clients:
"My Trusted Clients" = ca.sample.org
"Super Secret Client" = pocb.sample.org

I could then configure my CR/XDS/CSD channels (things that are usually accessed by all of clients) to accept client: "My Trusted Clients" , whereas something like "Top Secret" channels could be configured to accept "Super Secret Client". 

It is basically the same logic as you have now, just traverse the certification path up until you find a matching client.

**Comment by rcrichton** [comment]
Ok, I think that makes sense. I'm a little worried that implementations will use this instead of setting up proper authorisation for clients. But, I think it would be a useful feature to make admin's lives easier. What do others think? @devcritter @bausmeier

**Comment by devcritter** [comment]
Ultimately I think this as an implementation issue and all we can really do from our side is provide the mechanisms and leave it to implementors to decide on [policies](http://en.wikipedia.org/wiki/Separation_of_mechanism_and_policy). Perhaps we could have a flag in config to enable this feature, and if disabled do the stricter validation that we're doing now?

One implication though of having a single HIM client for multiple PoCs is that the transactions in the log will all be linked to this one client, making it difficult to determine which PoC a transaction. But that said for messages that contain the facility id, we can ensure that our mediators populate a property with this info so that the information's available on the console. Really just mentioning it so that it's on our radar.

**Comment by justin-fyfe** [comment]
+1 to making it a config option (would also disable it by default). 

This is low priority btw, the deployment in TZ will have relatively few clients to start with. It may even be appropriate to denote such an option as a different "class" of client or as a group (i.e. a domain rather than 'client').
