### ISSUE TITLE
Should mediators default channel config be manually added by a user rather than automatically added?

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#601]
@devcritter any thoughts?

**Comment by devcritter** [comment]
Yeah I'm in favour of manually adding. The automatic adding becomes a bit annoying at times, e.g. if you have existing channels that you'd rather use or you delete and re-add a mediator.

There's also an existing issue with regards to automatic adding for updates that we'll be able to close #214

**Comment by rcrichton** [comment]
Have you found the automatic channel creation to useful in any real world examples? I wonder if it is needed an all. It seems to be more confusing than helpful. It's good for getting up and running quickly, but I kinda feel like it would almost never do what you want and needs to be edited anyway. Perhaps people should rather be using the import/export function for initial (project specific) config.

**Comment by devcritter** [comment]
Hmmm yeah tbh I can't think of any use cases where the import function wouldn't have suited just fine. In fact that might work better since individual mediators often don't have the project-as-whole perspective. For the projects where we have multiple mediators, I'm starting to think I would prefer a single configuration json that we can just import once when setting up the HIM.

So yeah, agree perhaps we should just get rid of the defaultChannel field altogether.

**Comment by rcrichton** [comment]
That's kinda what I'm thinking to. It seems have been more annoying than useful.

**Comment by rcrichton** [comment]
@bausmeier @armageddon any thoughts about this before we decide to remove this functionality?
