### ISSUE TITLE
Tests are failing on e2e tests

### ISSUE THREAD

**Issue by hnnesv** [jembi/openhim-core-js#622]
All builds on Travis are failing ([e.g.](https://travis-ci.org/jembi/openhim-core-js/jobs/108220255)) with the following errors:
```
  1) e2e Integration Tests Authentication and authorisation tests Mutual TLS should forward a request to the configured routes if the client is authenticated and authorised:
     Uncaught Error: Parse Error
      at Error (native)
      at TLSSocket.socketOnData (_http_client.js:304:20)
      at readableAddChunk (_stream_readable.js:146:16)
      at TLSSocket.Readable.push (_stream_readable.js:110:10)
      at TLSWrap.onread (net.js:523:20)
  2) e2e Integration Tests Authentication and authorisation tests Mutual TLS "after each" hook:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:202:15)
      at TLSSocket.socketCloseListener (_http_client.js:234:23)
      at TCP._onclose (net.js:469:12)
```

I've been able to reproduce this on a clean VM (perhaps indicating a problem with an npm module...).

**Comment by hnnesv** [comment]
Looks like the problem happens when using on the latest node 4.x (4.3.0)

**Comment by rcrichton** [comment]
So, firstly thanks for @hnnesv for helping figure this out. So, the problem was with node v4.3.0's stricter HTTP headers parsing due to the [February security release](https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/). We finally traced the parse error to a rule that doesn't allow the `Content-Length` header (that Koa was adding) to be used with the `Transfer-Encoding: chunked` header that was being copied from the upstream response.

Thanks node for your super clear error message of `Parse Error`...
